#!/bin/bash

_cower() {
  local COWER cur prev opts ng

  COWER=$(type -P cower)
  [[ -z $COWER ]] && return 0

  _get_comp_words_by_ref cur prev

  # nullglob avoids problems when no results are found
  [[ -o nullglob ]] || { shopt -s nullglob; ng=1; }

  opts="-d --download -i --info -m --msearch -s --search -u --update -c --color
        -f --force -q --quiet -t --target -v --debug --ssl -h --help"

  # complete options
  if [[ $cur == -* ]]; then
    COMPREPLY=($(compgen -W "$opts" -- $cur))
  elif [[ $cur == --target= || $prev == '-t' ]]; then
    COMPREPLY=($(compgen -f -- $cur))
  elif [[ ${COMP_WORDS[@]} = *-@(!(-*)[di]*|-download|-info)* ]]; then
    COMPREPLY=($(compgen -W "$((( ${#cur} > 2 )) && $COWER -sq -- $cur 2>/dev/null)" -- $cur))
  fi

  # restore nullglob setting
  [[ $ng ]] && shopt -u nullglob

}

complete -F _cower cower
