#!/bin/bash

_cower() {
  local ng cower_exec cur prev opts src

  # nullglob avoids problems when no results found
  [[ ! -o nullglob ]] && { shopt -s nullglob; ng=1; }

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  cower_exec=$(type -P cower)
  [[ -z $cower_exec ]] && return 0

  opts="-d --download -i --info -s --search -u --update -c --color \
        -f --force -q --quiet -t --target -v --verbose"

  # complete options
  if [[ $cur == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts" -- $cur ) )
    return 0
  elif [[ $cur == --target= || $prev == '-t' ]]; then
    _filedir -d
    return 0
  fi

  # complete package names
  if [[ ${COMP_WORDS[@]} = *-@(!(-*)[di]*|-download|-info)* ]]; then
    COMPREPLY=( $(compgen -W "$([[ ${#cur} -ge 2 ]] && $cower_exec -sq $cur 2>/dev/null)" -- $cur ) )
  fi

  # restore nullglob setting if it was turned on
  [[ $ng ]] && shopt -u nullglob

}

complete -F _cower cower
