=head1 NAME

cower - a simple AUR downloader

=head1 SYNOPSIS

Usage: I<cower> [OPTIONS] E<lt>operationE<gt> PACKAGE [PACKAGE2...]

=head1 DESCRIPTION

cower is a simple tool to get information and download packages from the Arch User
Repository (AUR). It is written entirely in C.

=head1 OPERATIONS

=over 4

=item B<-d, --download>

Download I<PACKAGE>(s).
Pass this option twice to fetch dependencies.

=item B<-i, --info>

Show info for I<PACKAGES>(s). Pass this option twice to fetch more detailed info.

=item B<-s, --search>

Search for packages with the I<PACKAGE>(s) as the search term(s).

=item B<-u, --update>

Check foreign packages for updates in the AUR. Pass the -d flag as well to fetch updates,
if any, at the same time.

=back


=head1 OPTIONS

=over 4

=item B<-c, --color[=WHEN]>

Use colored output. WHEN is `never', `always' or `auto'. Color will be disabled in a pipe
unless WHEN is set to always.

=item B<--debug>

Display debug messages.

=item B<-f, --force>

Overwrite existing files when downloading.

=item B<-h, --help>

Display the help message and quit.

=item B<--ignore> <'pkg'>

Ignore a package upgrade. Can be used more than once. Also accepts a comma delimited list as
a single argument. Packages listed in pacman's IgnorePkg directive are honored.

=item B<-q, --quiet>

Output less.

=item B<-t, --target> <'dir'>

Download taurballs to alternate directory, specified by I<DIR>. Either a relative or absolute
path can be specified, but all components of the path must exist.

=back

=head1 CONFIGURATION

cower will look for a config file located at I<$XDG_CONFIG_HOME/cower/cower.conf>
and read color options from it in key=value format. Valid keys are:

=over 4

=item

B<repo>, B<packages>, B<uptodate>, B<outofdate>, B<url>, B<info>, B<warn>, B<error>

=back

Valid color values are:

=over 4

=item

B<BLACK>, B<BLUE>, B<CYAN>, B<FG>, B<GREEN>, B<MAGENTA>, B<RED>, B<WHITE>, B<YELLOW>

=back

All colors are also available in bold by prefixing BOLD (e.g. B<BOLDYELLOW>).

All keys and values are case sensitive. Comments, if desired, can be specfied with a #. If a
color is not specified, a default will prevail.

=head1 AUTHOR

Dave Reisner E<lt>d@falconindy.comE<gt>

