=head1 NAME

cower - a simple AUR downloader

=head1 SYNOPSIS

Usage: I<cower> [options] E<lt>operationE<gt> [ targets... ]

=head1 DESCRIPTION

cower is a simple tool to get information and download packages from the Arch
User Repository (AUR). Invoking cower consists of supplying an operation, any
applicable options, and usually one or more targets.

=head1 OPERATIONS

=over 4

=item B<-d, --download>

Download I<target>(s). Pass this option twice to fetch dependencies (done
recursively).

=item B<-i, --info>

Show info for I<targets>. Pass this option twice to fetch more detailed info.

=item B<-m, --msearch>

Search for packages maintained by target(s).

=item B<-s, --search>

Search for packages with the I<target>(s) as the search term(s). Extended regex
patterns are allowed as defined by POSIX are accepted.

B<Note:> This is more or less a hack because it's implemented on top of what
the AUR enforces for search rules.  The first span of non-regex characters in a
search string must be at least 2 characters long or the search will return no
results. This is not explicitly checked at runtime.

=item B<-u, --update>

Check foreign packages for updates in the AUR. Without any arguments, all
manually installed packages will be checked. If targets are supplied, only
those targets will be checked. This operation can be combined with the
--download operation.

=back


=head1 OPTIONS

=over 4

=item B<-c, --color[=WHEN]>

Use colored output. WHEN is `always' or `auto'. Color will be disabled in a
pipe unless WHEN is set to always.

=item B<-v, --debug>

Show debug output. This option should be passed first if used.

=item B<-f, --force>

Overwrite existing files when downloading.

=item B<-h, --help>

Display the help message and quit.

=item B<--ignore> <'pkg'>

Ignore a package upgrade. Can be used more than once. Also accepts a comma
delimited list as a single argument. Packages listed in pacman's IgnorePkg
directive are honored.

=item B<-q, --quiet>

Output less.

=item B<--ssl>

Establish secure connections over https.

=item B<-t, --target> <'dir'>

Download taurballs to alternate directory, specified by I<DIR>. Either a
relative or absolute path can be specified, but all components of the path must
exist.

=item B<--threads> <'num'>

Limit the number of threads created, with a default of 20. In practice, you
should never need to bother with this setting. Other than the case of an
--update operation with no targets specified, a thread is created for each
target provided to cower. If cower has fewer targets than threads specified,
the number of threads created will instead be the number of targets.

=item B<-v, --verbose>

Output more. This primarily affects the update operation.

=back

=head1 AUTHOR

Dave Reisner E<lt>d@falconindy.comE<gt>

