=head1 NAME

cower - a simple AUR agent

=head1 SYNOPSIS

Usage: I<cower> [OPTIONS] E<lt>operationE<gt> PACKAGE [PACKAGE2...]

=head1 DESCRIPTION


cower is a simple tool to get information and download packages from the Arch User
Repository (AUR). It is written entirely in C.


=head1 OPTIONS


=head2 Operations



=over 4


=item B<-d, --download>

Download I<PACKAGE>(s).
Pass this option twice to fetch dependencies.


=item B<-i, --info>

Show info for I<PACKAGES>(s).


=item B<-s, --search>

Search for packages with the I<PACKAGE>(s) as the search term(s).


=item B<-u, --update>

Check foreign packages for updates in the AUR. Pass the -d flag as well to fetch updates,
if any, at the same time.


=back



=head2 Options



=over 4


=item B<-c, --color>

Use colored output.


=item B<-f, --force>

Overwrite existing files when downloading.


=item B<-q, --quiet>

Output less.


=item B<-t> I<DIR>B<, --target=>I<DIR>

Download taurballs to alternate directory, specified by I<DIR>. Either a relative or absolute
path can be specified, but all components of the path must exist.


=item B<-v, --verbose>

Be more verbose. Pass this option twice to show debug information.


=back



=head1 AUTHOR

Dave Reisner E<lt>d@falconindy.comE<gt>

